# pymysql.err.OperationalError
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
<!-- incorrect password -->

# NameError
NameError: name 'self' is not defined
<!-- didn't pass in self -->

# SyntaxError: invalid syntax
<!-- forgot "" for a string -->

# NameError
NameError: name 'true' is not defined
<!-- true needs to be True in python -->

# SyntaxError: invalid syntax
  print("Running Query:", query)
    ^
<!-- print line not tabbed correctly -->

# AttributeError
AttributeError: 'MySQLConnection' object has no attribute 'connection'
<!-- + instead of a = -->
